docs: apple_vision_pro_info.pdf
model_API_keys:
  palm: model_API_keys/palm_api.txt
params:
  chain_type: stuff
  chunk_overlap: 20
  chunk_size: 500
  embedding_device: cuda
  embedding_model: sentence-transformers/all-MiniLM-L6-v2
  k: 3
  llm: google/flan-t5-base
  llm_device: cuda
  max_length: 2048
  quantize: true
  query_instruction: Represent the question for retrieving supporting documents
  repetition_penalty: 1.15
  search_type: similarity
  separator: \n\n
  temperature: 0.1
  top_p: 0.95
